version: '2.3'
services:

  #
  # Platform Data
  #
  # Get data from dockerhub to run various services
  #

  platform_data:
    container_name: jolibrain_platform_data
    image: jolibrain/platform_data:latest
    user: ${CURRENT_UID}
    volumes:
      - ${DD_PLATFORM}:/platform

  #
  # Platform UI
  #
  # Serving react container
  #

  platform_ui:
    container_name: jolibrain_platform_ui
    image: jolibrain/platform_ui:latest
    restart: always
    volumes:
      - platform_ui:/usr/share/nginx/html
      - ./config/platform_ui/config.json:/usr/share/nginx/html/config.json

  #
  # Deepdetect
  #

  deepdetect:
    container_name: jolibrain_deepdetect
    image: 'jolibrain/deepdetect_cpu'
    restart: always
    user: ${CURRENT_UID}
    volumes:
      - ${DD_PLATFORM}:/opt/platform

  #
  # nginx
  #
  # modify port 80 to change facade port
  #

  nginx:
    container_name: jolibrain_nginx
    image: nginx:latest
    restart: always
    ports:
      - '1912:80'
    links:
      - jupyter:jupyter
      - deepdetect:deepdetect
      - filebrowser
    volumes:
      - platform_ui:/var/www/html
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ${DD_PLATFORM}/docs/public:/var/www/html/docs
      - ${DD_PLATFORM}:/opt/platform
      - ./config/platform_ui/config.json:/var/www/html/config.json

  #
  # Jupyter notebooks
  #

  jupyter:
    container_name: jolibrain_jupyter
    environment:
      - JUPYTER_LAB_ENABLE=yes
      - NB_UID=${MUID}
    image: jolibrain/jupyter_dd_notebook
    volumes:
      - ${DD_PLATFORM}:/opt/platform
      - ${DD_PLATFORM}/notebooks:/home/jovyan/work
      - ./config/jupyter:/home/jovyan/.jupyter

  #
  # doc
  #
  docs:
    container_name: jolibrain_docs
    image:  jolibrain/platform_docs

  #
  # filebrowser
  #
  filebrowser:
    container_name: jolibrain_filebrowser
    image: filebrowser/filebrowser:v1.10.0
    restart: always
    user: ${CURRENT_UID}
    volumes:
      - ${DD_PLATFORM}:/srv
      - ${DD_PLATFORM}/filebrowser/database.db:/etc/database.db
      - ./config/filebrowser/config.json:/config.json

volumes:
  platform_ui:
